name: Ubuntu 18.04

on: 
  workflow_dispatch:
    inputs:
      uname:
        description: Enter your username
        required: true
        default: 'administrator'
      pword:
        description: Enter your password
        required: true
        default: '123456'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Wait a moment for start the setup
        run: sudo bash ./linux_config/setting.sh > /dev/null 2>&1
      - name: Creating User to Login
        run: sudo useradd -m ${{ github.event.inputs.uname }} && sudo adduser ${{ github.event.inputs.uname }} sudo && echo '${{ github.event.inputs.uname }}:${{ github.event.inputs.pword }}' | sudo chpasswd
      - name: Starting Ngrok
        run: |
         ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}
         ./ngrok tcp 3389 > /dev/null &
      - name: YOU IP
        run: |
          echo Link for VNC
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
      - name: Now can connect! The limit is 6H
        run: sleep 21600
