name: Ubuntu 18.04

on: 
  workflow_dispatch:
    inputs:
      uname:
        description: Enter your username
        required: true
        default: 'administrator'
      pword:
        description: Enter your password
        required: true
        default: '123456'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # Install Desktop Environment
      - name: Install Sudo
        run: sudo apt-get update
      - name: Opening the system VNC
        run: sudo apt install xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils > /dev/null 2>&1
      - name: Wait a moment for start the setup
        run: sudo bash ./linux_config/setting.sh 
        
      - name: YOU IP
        run: |
          echo Link for VNC
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
      - name: Ubuntu ready to go  with limit 6H
        run: sleep 21600
