name: Ubuntu 18.04

on: 
  workflow_dispatch:
    inputs:
      uname:
        description: Enter your username
        required: true
      pword:
        description: Enter your password
        required: true
        default: '123456'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          sudo bash ./linux_config/setting.sh ${{ github.event.inputs.uname }} ${{ github.event.inputs.pword }} ${{ secrets.NGROK_TOKEN }}
      - name: Ubuntu ready to go 
        run: sleep 1d
