name: Ubuntu 18.04

on: 
  workflow_dispatch:
    inputs:
      username:
        description: Enter your username:
        required: true
      password:
        description: Enter your password
        required: true
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          #sudo bash ./linux_config/setting.sh ${{ github.event.inputs.username }} ${{ github.event.inputs.password }} ${{ secrets.NGROK_TOKEN }}
          sudo bash ./linux_config/setting.sh
      - name: Ubuntu ready to go 
        run: sleep 1d
